runtime: custom
env: flex

service: anecdote-surveys-backend

env_variables:
  DATABASE_URL:
  EMAIL_VERIFICATION_DISABLED:
  ENCRYPTION_KEY:
  NEXTAUTH_SECRET:
  NEXTAUTH_URL:
  PASSWORD_RESET_DISABLED:
  POSTGRES_PASSWORD:
  WEBAPP_URL:

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8

network:
  name: anecdote-vpc
  subnetwork_name: public-us-east1-2

resources:
  cpu: 8
  memory_gb: 32
  disk_size_gb: 128
